kind: pipeline
type: docker
name: shop-mobile

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
    when:
      branch:
        - main
      event:
        - push

  - name: build
    image: node:14.16
    commands:
      - npm config set registry https://registry.npm.taobao.org/
      - npm install
      - npm run build
    when:
      branch:
        - main
      event:
        - push

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    when:
      branch:
        - main
      event:
        - push

  - name: push-docker
    image: plugins/docker
    settings:
      mirror: https://docker.mirrors.ustc.edu.cn
      registry: registry.cn-qingdao.aliyuncs.com
      repo: registry.cn-qingdao.aliyuncs.com/sky_55/util-box
      tag: ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: cache
    host:
      path: /data/node_modules_cache
  - name: docker
    host:
      path: /var/run/docker.sock
